### ISSUE TITLE
Research clustering methods / visualizations for large codebases

### ISSUE THREAD

**Issue by etagwerker** [julianrubisch/attractor#38]
Hey @julianrubisch,

Your project is very interesting! Thanks for sharing it with the community. 

I did a quick report with the `e-petitions` project which is a Rails application. I used this branch: https://github.com/fastruby/e-petitions/tree/attractor

Unfortunately the data in the plot chart looks a little too cluttered: 

![Screen Shot 2019-09-28 at 2 46 52 PM](https://user-images.githubusercontent.com/17584/65821114-55913300-e1ff-11e9-9ca8-503435e5ab31.png)

It's hard to see what files are closer to the X and Y axis. If I select some of the section, I see a bit more in detail: 

![Screen Shot 2019-09-28 at 2 48 14 PM](https://user-images.githubusercontent.com/17584/65821139-a6a12700-e1ff-11e9-8367-e0dd74fd1e7f.png)

What would be a better way to display that information? Maybe it could be a bigger graph? 

Anyway, I thought I should submit this issue to start a conversation. 😄 

Thanks!

**Comment by julianrubisch** [comment]
Hi @etagwerker,

you are right and yes, I‘m working on a few features to improve on that situation. (i.e., filtering from the UI)

First of all, have you tried running it with a path prefix (-p option)?

**Comment by julianrubisch** [comment]
I was just thinking, as another option we could introduce a clustering algorithm for the points, either simple k means

http://bl.ocks.org/feyderm/75c18a9143aac50a24e392762f10d6a4

or maybe even more useful, quadtrees: https://github.com/d3/d3-quadtree

**Comment by julianrubisch** [comment]
http://bl.ocks.org/ganeshv/6a8e9ada3ab7f2d88022

https://observablehq.com/@d3/treemap
