### ISSUE TITLE
`attractor report` generates a reference box with NaN values 

### ISSUE THREAD

**Issue by etagwerker** [julianrubisch/attractor#40]
Hey @julianrubisch, 

The reference box for the churn vs. complexity graph is showing: 

![Screen Shot 2019-09-29 at 10 44 09 AM](https://user-images.githubusercontent.com/17584/65834147-21bd1880-e2a6-11e9-9f3c-97ec45719c06.png)

```
y = NaN x ^ NaN
R^2 = NaN
```

This is the project and branch that I used: https://github.com/fastruby/e-petitions/tree/attractor

The command that I ran: `attractor report`

I'm not sure what could be wrong. That application is an open source, Rails app. The generated report is over here: https://fastruby.github.io/quality/e-petitions/attractor_output/index.html 

Let me know if I can provide more details. 

Thanks!

**Comment by julianrubisch** [comment]
Hey and thanks again for reporting!

The problem is very likely a division by zero somewhere in the d3 regression. 

I‘m aware of it, but having a distinct issue for it is 👍🏻

Probably need to filter the input data for 0s. I’ll look into it later

**Comment by julianrubisch** [comment]
Fixed in 0.4.1
