### ISSUE TITLE
Idea: Label X Axis and Y Axis 

### ISSUE THREAD

**Issue by etagwerker** [julianrubisch/attractor#41]
Hey @julianrubisch, 

It is a little hard to interpret the X/Y graph: 

![Screen Shot 2019-09-29 at 10 44 09 AM](https://user-images.githubusercontent.com/17584/65834161-53ce7a80-e2a6-11e9-89c1-b038c2d3560a.png)

Do you think it would be a good idea to label the X/Y axis? 

I assume the X axis is churn and the Y axis is complexity. 

Let me know. 

Thanks!

**Comment by julianrubisch** [comment]
Very well! Do you by chance know a little d3 to submit a PR?

**Comment by etagwerker** [comment]
@julianrubisch You beat me to it. Thank you! :)

**Comment by julianrubisch** [comment]
Released in 0.4.2, you’re welcome
