### ISSUE TITLE
Add option to specify target dir

### ISSUE THREAD

**Issue by palkan** [julianrubisch/attractor#5]
First of all, thanks for the tool. It's really helpful (event at this early stage).

Here is an idea for future enhancements: having an ability to narrow the analysis to a particular folder. For example:

```sh
attractor calc app/models
```

First, the chart could become barely readable when the number of the project files is huge.

Secondly, sometimes it could be useful to pay attention only to a particular group of files (e.g., in Rails that could be models, controllers, etc.).

Right now I've wrapped attractor into a custom executable with the following code:

```ruby
TARGET_DIR = ARGV[1] || "app"

$stdout.puts "Generate churn/complexity report for: #{TARGET_DIR}"

Attractor::Calculator.singleton_class.prepend(Module.new do
  def calculate(*)
    super.select { |v| v.file_path.start_with?(TARGET_DIR) }
  end
end)

Attractor::Calculator.report
$stdout.puts "Done. See attractor_output/index.html"
```

Not proposing a PR, 'cause it seems that it's too early for the project. So, sharing the idea instead.

**Comment by julianrubisch** [comment]
Thanks for the input!

That’s actually exactly what I had in mind here: https://github.com/julianrubisch/attractor/issues/3

I‘m just probably prepare another PR for the churn gem first, to also improve performance, because there’s no need to calculate churn for the whole git directory in the first place!

**Comment by julianrubisch** [comment]
I think that should have done it: 

https://github.com/julianrubisch/attractor/pull/7

Feel free to reopen if it's buggy...

**Comment by palkan** [comment]
Thanks!
