### ISSUE TITLE
Exclusion list of files/dirs/patterns ?

### ISSUE THREAD

**Issue by mtancoigne** [julianrubisch/attractor#90]
Hi !

I'm currently testing Attractor and something bothers me: it seems impossible to specify an exclusion list of files/dirs.
My use case is mainly for ignoring generated files (e.g.: `db/schema.rb`) or imported code from the outside world...

Is it planned in a future version?
Are you interested in a MR or something? (I don't know if i'll have time tho).

**Comment by julianrubisch** [comment]
Hi!

You are right, there is a whitelist option, but not a blacklist option... I'll put it on my list - if you have time, don't hesitate to put up a PR if you get to it!

**Comment by mtancoigne** [comment]
A PR with a few work is now open: #92
