### ISSUE TITLE
Watch option is broken

### ISSUE THREAD

**Issue by mtancoigne** [julianrubisch/attractor#91]
Hello again !

Starting attractor with `attractor calc --watch` fails with:

```text
lib/attractor/watcher.rb:14:in `watch': uninitialized constant Attractor::Watcher::Listen
```

Same happens with `report --watch` (but report gets created once)

`serve --watch` results in a blank page (no graph and JS errors in browser console) but no error in terminal

When requiring `listen` in `watcher.rb`, it still fails with 

```text
gems/listen-3.4.1/lib/listen/adapter/config.rb:16:in `realpath': No such file or directory @ rb_check_realpath_internal -  (Errno::ENOENT)
```

**Comment by julianrubisch** [comment]
Thanks for the report! Could you post your ruby version for reference?

**Comment by mtancoigne** [comment]
The project in which I use Attractor uses Ruby 2.7.0

**Comment by mtancoigne** [comment]
The same happens on ruby 2.5.5 (empty Rails project using Ruby 2.5.5)

**Comment by mtancoigne** [comment]
By requiring 'listen' in `lib/attractor/watcher.rb`, it works on Ruby 2.5.5, but not on 2.7:

```text
.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/adapter/config.rb:16:in `realpath': No such file or directory @ rb_check_realpath_internal -  (Errno::ENOENT)
```

**Comment by julianrubisch** [comment]
I reserved some time for your issues, but need to resolve some other things first 👍

**Comment by julianrubisch** [comment]
closing in on the problem... takeaway no1: the error only appears when you don't specify a file prefix

**Comment by julianrubisch** [comment]
Put up a PR here, care to try it out/review it?
https://github.com/julianrubisch/attractor/pull/94

**Comment by julianrubisch** [comment]
Note that I haven't dealt with the `serve` watcher yet... likely I'll either yank that or fix it later!

**Comment by mtancoigne** [comment]
I'll check right now !

**Comment by mtancoigne** [comment]
It's working with ruby 2.7 now!

**Comment by julianrubisch** [comment]
Great thanks!

**Comment by julianrubisch** [comment]
Merged. I'll cut a patch release later. Thanks for your efforts!

**Comment by mtancoigne** [comment]
I'll continue on the PR then :)

**Comment by julianrubisch** [comment]
Yep, please rebase!
